name: Deploy to GitHub Pages

# ワークフローの実行トリガーを設定（mainブランチへのプッシュ時）
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.jsをセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # npm installを実行
      - name: Install dependencies
        run: npm install

      # npm run buildを実行
      - name: Build project
        run: npm run build

      # ビルド結果をGitHub Pagesにデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # デフォルトではgh-pagesブランチがデプロイ先
          destination_dir: ''
